export const RECIPES_LOADING = 'RECIPES_LOADING';
export const RECIPES_FETCH_FAILED = 'RECIPES_FETCH_FAILED';
export const ADD_RECIPES = 'ADD_COURSES';
export const RECIPE_LOADING = 'RECIPE_LOADING';
export const RECIPE_FETCH_FAILED = 'RECIPE_FETCH_FAILED';
export const ADD_RECIPE = 'ADD_RECIPE';